#!/usr/bin/env python3
"""
Project Phoenix Stage 2A TI model binder.

Run from the repository root:
    python tools\\bind_stage2a_models.py

The script:
- verifies the exact TI model SHA-256 hashes observed during preparation;
- verifies the expected top-level .SUBCKT interfaces;
- checks whether LM317 OUT_1 is referenced anywhere except the .SUBCKT declaration;
- generates a bound Stage-2A smoke-test deck only if all checks pass.
"""

from __future__ import annotations

import hashlib
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
LM317 = ROOT / "electronics/spice/models/ti/extracted/LM317/LM317_TRANS.LIB"
LM337 = ROOT / "electronics/spice/models/ti/extracted/LM337/LM337_N_TRANS.LIB"

EXPECTED = {
    LM317: "9b56d7c68b75d3c0fd1e0b55f5ddc448f89f82984f026ff31acdf89bde4bd7e1",
    LM337: "dc9fd0b650ce944f69654e7c5ebe1bb68dae541b25d92633825973afe2c7d4ff",
}

OUT = ROOT / "electronics/spice/PHX_ARCH_C_stage2a_smoke.cir"

def sha256(path: pathlib.Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def subckt_decl(text: str, name: str) -> str | None:
    m = re.search(rf"(?im)^\s*\.subckt\s+{re.escape(name)}\s+([^\r\n]+)", text)
    return m.group(1).strip() if m else None

def fail(msg: str) -> None:
    print(f"FAIL: {msg}")
    raise SystemExit(2)

for path, expected in EXPECTED.items():
    if not path.exists():
        fail(f"missing model file: {path}")
    actual = sha256(path)
    print(f"{path.name}: {actual}")
    if actual.lower() != expected.lower():
        fail(f"SHA-256 mismatch for {path.name}")

t317 = LM317.read_text(encoding="utf-8", errors="replace")
t337 = LM337.read_text(encoding="utf-8", errors="replace")

d317 = subckt_decl(t317, "LM317_TRANS")
d337 = subckt_decl(t337, "LM337_N_TRANS")

print(f"LM317_TRANS nodes: {d317}")
print(f"LM337_N_TRANS nodes: {d337}")

if d317 != "IN ADJ OUT_0 OUT_1":
    fail(f"unexpected LM317 interface: {d317!r}")
if d337 != "IN ADJ OUT":
    fail(f"unexpected LM337 interface: {d337!r}")

body317 = re.sub(
    r"(?im)^\s*\.subckt\s+LM317_TRANS\s+[^\r\n]+",
    "",
    t317,
    count=1,
)
out1_refs = len(re.findall(r"(?i)\bOUT_1\b", body317))
print(f"LM317 OUT_1 references outside declaration: {out1_refs}")
if out1_refs != 0:
    fail("LM317 OUT_1 is used by the model body; automatic floating-node binding is unsafe")

deck = r"""* Project Phoenix - Architecture C Stage 2A TI regulator smoke test
* GENERATED by tools/bind_stage2a_models.py after model hash/interface checks.
*
* TI model provenance:
* LM317_TRANS.LIB SHA256:
*   9b56d7c68b75d3c0fd1e0b55f5ddc448f89f82984f026ff31acdf89bde4bd7e1
* LM337_N_TRANS.LIB SHA256:
*   dc9fd0b650ce944f69654e7c5ebe1bb68dae541b25d92633825973afe2c7d4ff
*
* LM317 model interface: IN ADJ OUT_0 OUT_1
* OUT_1 was verified unused in the model body and is bound to isolated node nc317.
* LM337 model interface: IN ADJ OUT

.param VRAW=55
.param RIPPLE=2
.param FLINE=100
.param RZ=3.9k
.param CZ=47u
.param ILOAD=4.7m
.param VZ=24
.param BFBJT=15

VRAW_P rawp 0 SINE({VRAW} {RIPPLE} {FLINE})
VRAW_N rawn 0 SINE({-VRAW} {RIPPLE} {FLINE})

RZP rawp zbp {RZ}
DZP 0 zbp DZ24
CZP zbp 0 {CZ}
QPASS_P rawp zbp prep TIP41C_BOUNDED

RZN rawn zbn {RZ}
DZN zbn 0 DZ24
CZN zbn 0 {CZ}
QPASS_N rawn zbn pren TIP42C_BOUNDED

R1P outp adjp 120
R2P adjp 0 1.50k
R1N outn adjn 120
R2N adjn 0 1.50k

COUTP outp 0 10u
COUTN 0 outn 10u

IP_LOAD outp 0 {ILOAD}
IN_LOAD 0 outn {ILOAD}

.include "models/ti/extracted/LM317/LM317_TRANS.LIB"
.include "models/ti/extracted/LM337/LM337_N_TRANS.LIB"

XU317 prep adjp outp nc317 LM317_TRANS
XU337 pren adjn outn LM337_N_TRANS

.model DZ24 D(BV={VZ} IBV=5m RS=1 N=1.2 CJO=200p)
.model TIP41C_BOUNDED NPN(IS=1e-12 BF={BFBJT} VAF=75 IKF=1 CJE=300p CJC=150p)
.model TIP42C_BOUNDED PNP(IS=1e-12 BF={BFBJT} VAF=75 IKF=1 CJE=300p CJC=150p)

.tran 0 300m 0 20u startup

.meas TRAN PREP_AVG AVG V(prep) FROM 250m TO 300m
.meas TRAN PREN_AVG AVG V(pren) FROM 250m TO 300m
.meas TRAN OUTP_AVG AVG V(outp) FROM 250m TO 300m
.meas TRAN OUTN_AVG AVG V(outn) FROM 250m TO 300m
.meas TRAN OUTP_PP PP V(outp) FROM 250m TO 300m
.meas TRAN OUTN_PP PP V(outn) FROM 250m TO 300m
.meas TRAN IZP_AVG AVG -I(DZP) FROM 250m TO 300m
.meas TRAN IZN_AVG AVG -I(DZN) FROM 250m TO 300m

.end
"""

OUT.write_text(deck, encoding="utf-8", newline="\n")
print(f"PASS: generated {OUT}")
print("Next: open PHX_ARCH_C_stage2a_smoke.cir in LTspice and run it.")
